import React from 'react';
import { roboto } from '../packages/@common/ui/styles/font';
import { GlobalStyles } from '../packages/@common/ui/styles/globalStyles';
import NextThemeProvider from '../providers/NextThemeProvider';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={roboto.className}>
            <body>
                <GlobalStyles />
                <NextThemeProvider mode="light">{children}</NextThemeProvider>
            </body>
        </html>
    );
}
